---
# Default is the current working directory.
# base_dir:

role:
  autodetect: true

dry_run: false
# exclude_files: []
# exclude_tags: []

logging:
  level: "info"
  json: false

template:
  name: readme
  # src:

renderer:
  include_header: "HEADER.md"
  force_overwrite: true
