---
- name: Install fastfetch requirements
  ansible.builtin.package:
    name: "{{ fastfetch_dependencies.deb_based }}"

- name: Get 'glib' version
  block:
    - name: Get latest available 'glib' version
      changed_when: false
      register: glib_version
      ansible.builtin.shell:
        cmd: set -o pipefail; {{ ansible_facts.pkg_mgr }} info libc6 2>/dev/null | grep -E ^Version | grep -Eo '[0-9]\.[0-9]+'
        executable: /bin/bash

- name: Install fastfetch package
  block:
    - name: Install compatible fastfetch package
      when: glib_version.stdout is version(fastfetch_glib_requirement_latest, 'lt')
      block:
        - name: DEBUG | Compatible fastfetch package URL
          ansible.builtin.debug:
            msg: "https://github.com/{{ fastfetch_github_orga }}/{{ fastfetch_github_repo }}/releases/download/{{ fastfetch_fallback_version }}/fastfetch-{{ fastfetch_fallback_version
              }}-{{ ansible_facts.system }}.{{ fastfetch_pkg_ext }}"
        - name: Install compatible fastfetch package
          ansible.builtin.apt:
            deb: "https://github.com/{{ fastfetch_github_orga }}/{{ fastfetch_github_repo }}/releases/download/{{ fastfetch_fallback_version }}/fastfetch-{{ fastfetch_fallback_version
              }}-{{ ansible_facts.system }}.{{ fastfetch_pkg_ext }}"
            state: present
    - name: Install latest fastfetch package
      when: glib_version.stdout is version(fastfetch_glib_requirement_latest, 'ge')
      block:
        - name: DEBUG | Latest fastfetch package URL
          ansible.builtin.debug:
            msg: "https://github.com/{{ fastfetch_github_orga }}/{{ fastfetch_github_repo }}/releases/download/{{ curl_output.json.tag_name }}/fastfetch-{{ ansible_facts.system
              | lower }}-{{ parsed_arch }}.{{ fastfetch_pkg_ext }}"
        - name: Install latest fastfetch package
          ansible.builtin.apt:
            deb: "https://github.com/{{ fastfetch_github_orga }}/{{ fastfetch_github_repo }}/releases/download/{{ curl_output.json.tag_name }}/fastfetch-{{ ansible_facts.system
              | lower }}-{{ parsed_arch }}.{{ fastfetch_pkg_ext }}"
            state: present
  rescue:
    - name: DEBUG | Print sorry message
      ansible.builtin.debug:
        msg: "Sorry, this host seems not to be compatible with fastfetch. Maybe try it manually."
