---
name: CI Pipeline

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: "ansible-role-fastfetch"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: "ansible-role-fastfetch"

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install test dependencies
        run: pip3 install -q yamllint

      - name: Run tests
        run: yamllint .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - "debian13"
          - "rockylinux9"
          - "ubuntu2404"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: "ansible-role-fastfetch"

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install test dependencies
        run: pip3 install -r requirements.dev.txt

      - name: Run tests
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
